apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hub-frontend
  name: hub-frontend
  namespace: hcodedata
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hub-frontend
  template:
    metadata:
      labels:
        app: hub-frontend
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/hcodedata/hub-frontend:${TAG}
          name: hub-frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "30m"
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
